language: cpp
sudo: required

compiler:
- gcc

# Install Boost from default repository
before_script:
- sudo add-apt-repository universe
- sudo apt-get update
- sudo apt install libboost-dev
- sudo apt install libboost-all-dev
- pip install codecov

script:
- cmake -DBUILD_TYPE=Travis .
- make
- sudo make install
- pip install urllib3[secure]
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
