language: cpp
dist: trusty
sudo: required

compiler:
	- gcc

before_script:
	# Add Boost 1.57 PPA
	- sudo add-apt-repository ppa:afrank/boost
	- sudo apt-get update -qq
	- sudo apt-get install libboost-test-dev

script:
	- cmake .
	- make
