language: cpp
sudo: required

compiler:
- gcc

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - boost1.67

before_script:
- sudo pip install codecov

script:
- cmake -DBUILD_TYPE=Travis .
- make
- sudo make install
- pip install urllib3[secure]
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
