language: cpp
sudo: required

compiler:
- gcc

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - boost1.67
      - lcov

before_script:
- sudo pip install codecov
- sudo pip install cpplint

script:
- cmake -DBUILD_TYPE=Travis "-DCMAKE_CXX_CPPLINT=cpplint;--filter=-whitespace/tab,-build/include_subdir" .
- make
- sudo make install
- pip install --user urllib3[secure]
- make coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
